// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgqueries

import (
	"time"

	"github.com/google/uuid"
)

type University struct {
	ID           uuid.UUID
	Title        string
	Login        string
	PasswordHash string
	Inn          string
	Confirmed    bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
